// Dades de prova inicials per al magatzem de dades en memòria
import type { Pacient, Sessio } from "@/types";

export const PACIENTS_INICIALS: Pacient[] = [
  {
    id: "1",
    nom: "Maria",
    cognoms: "Guasch",
    dataNaixement: "1974-03-15",
    telefon: "612 345 678",
    email: "maria.guasch@email.com",
    diagnostic: "Dolor lumbar crònic",
    fase: "cronic",
    profesionalAssignat: "Marc Soler, fisioterapeuta",
    estat: "actiu",
    dataInici: "2025-11-03",
    properaSessio: "2026-06-22",
    frequencia: "Setmanal",
  },
  {
    id: "2",
    nom: "Josep",
    cognoms: "Roca",
    dataNaixement: "1988-02-10",
    telefon: "634 221 109",
    email: "josep.roca@email.com",
    diagnostic: "Postoperatori de genoll",
    fase: "agut",
    profesionalAssignat: "Marc Soler, fisioterapeuta",
    estat: "actiu",
    dataInici: "2026-04-15",
    properaSessio: "2026-06-20",
    frequencia: "2 cops per setmana",
  },
  {
    id: "3",
    nom: "Anna",
    cognoms: "Torres",
    dataNaixement: "1958-11-02",
    telefon: "699 884 221",
    email: "anna.torres@email.com",
    diagnostic: "Ictus · rehabilitació",
    fase: "subagut",
    profesionalAssignat: "Marc Soler, fisioterapeuta",
    estat: "actiu",
    dataInici: "2026-02-10",
    properaSessio: "2026-06-18",
    frequencia: "3 cops per setmana",
  },
  {
    id: "4",
    nom: "Pere",
    cognoms: "Vidal",
    dataNaixement: "1981-08-05",
    telefon: "611 552 998",
    email: "pere.vidal@email.com",
    diagnostic: "Cervicàlgia",
    fase: "agut",
    profesionalAssignat: "Marc Soler, fisioterapeuta",
    estat: "alta temporal",
    dataInici: "2026-01-12",
  },
  {
    id: "5",
    nom: "Laia",
    cognoms: "Mas",
    dataNaixement: "1996-09-30",
    telefon: "655 332 871",
    email: "laia.mas@email.com",
    diagnostic: "Esquinç de turmell",
    fase: "agut",
    profesionalAssignat: "Marc Soler, fisioterapeuta",
    estat: "actiu",
    dataInici: "2026-05-20",
    properaSessio: "2026-06-17",
    frequencia: "Setmanal",
  },
];

export const SESSIONS_INICIALS: Sessio[] = [
  {
    id: "1-3",
    pacientId: "1",
    numero: 3,
    data: "2026-06-08",
    titol: "Seguiment: millora de la mobilitat lumbar",
    previewResum:
      "La pacient reporta una reducció notable del dolor (EVA 3/10) i més confiança en els moviments de flexió de tronc.",
    evolucio: "millora",
    eva: 3,
  },
  {
    id: "1-2",
    pacientId: "1",
    numero: 2,
    data: "2026-05-25",
    titol: "Valoració funcional i control motor",
    previewResum:
      "Es manté el dolor lumbar amb EVA 5/10. S'observa por al moviment en les flexions completes de tronc.",
    evolucio: "estable",
    eva: 5,
    deteccionsIA: [
      {
        tipus: "kinesiofobia",
        descripcio:
          "La pacient evita certs moviments per por a augmentar el dolor.",
        severitat: "warning",
      },
    ],
  },
  {
    id: "1-1",
    pacientId: "1",
    numero: 1,
    data: "2026-05-11",
    titol: "Primera visita: avaluació inicial",
    previewResum:
      "Dolor lumbar crònic d'inici fa 8 mesos, EVA 6/10. S'inicia pla de tractament amb exercici terapèutic.",
    evolucio: "estable",
    eva: 6,
  },
];
